---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: <WORKER_NAME>
  namespace: openshift-machine-api
  labels:
    dpu-capable: "true"
spec:
  online: false
  bootMACAddress: <BOOT_MAC>
  rootDeviceHints:
    deviceName: <ROOT_DEVICE>
  bmc:
    address: redfish-virtualmedia+https://<BMC_IP>
    credentialsName: <WORKER_NAME>-bmc-secret
    disableCertificateVerification: true
