---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpf-controller-metrics-reader
  namespace: dpf-operator-system
---
apiVersion: v1
kind: Secret
metadata:
  name: dpf-controller-metrics-reader-token
  namespace: dpf-operator-system
  annotations:
    kubernetes.io/service-account.name: dpf-controller-metrics-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dpf-controller-metrics-reader
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dpf-controller-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dpf-controller-metrics-reader
subjects:
  - kind: ServiceAccount
    name: dpf-controller-metrics-reader
    namespace: dpf-operator-system
